<?php

return array (
    'url' => 'https://api.github.com/repos/agallou/test/pulls/1',
    'id' => 66762748,
    'html_url' => 'https://github.com/agallou/test/pull/1',
    'diff_url' => 'https://github.com/agallou/test/pull/1.diff',
    'patch_url' => 'https://github.com/agallou/test/pull/1.patch',
    'issue_url' => 'https://api.github.com/repos/agallou/test/issues/1',
    'number' => 1,
    'state' => 'open',
    'locked' => false,
    'title' => 'test 1',
    'user' =>
        array (
            'login' => 'agallou',
            'id' => 320372,
            'avatar_url' => 'https://avatars.githubusercontent.com/u/320372?v=3',
            'gravatar_id' => '',
            'url' => 'https://api.github.com/users/agallou',
            'html_url' => 'https://github.com/agallou',
            'followers_url' => 'https://api.github.com/users/agallou/followers',
            'following_url' => 'https://api.github.com/users/agallou/following{/other_user}',
            'gists_url' => 'https://api.github.com/users/agallou/gists{/gist_id}',
            'starred_url' => 'https://api.github.com/users/agallou/starred{/owner}{/repo}',
            'subscriptions_url' => 'https://api.github.com/users/agallou/subscriptions',
            'organizations_url' => 'https://api.github.com/users/agallou/orgs',
            'repos_url' => 'https://api.github.com/users/agallou/repos',
            'events_url' => 'https://api.github.com/users/agallou/events{/privacy}',
            'received_events_url' => 'https://api.github.com/users/agallou/received_events',
            'type' => 'User',
            'site_admin' => false,
        ),
    'body' => '',
    'created_at' => '2016-04-17T09:11:28Z',
    'updated_at' => '2016-04-17T09:15:38Z',
    'closed_at' => NULL,
    'merged_at' => NULL,
    'merge_commit_sha' => 'e881b7c70d5688cf364cb51fe11406eee074172a',
    'assignee' => NULL,
    'milestone' => NULL,
    'commits_url' => 'https://api.github.com/repos/agallou/test/pulls/1/commits',
    'review_comments_url' => 'https://api.github.com/repos/agallou/test/pulls/1/comments',
    'review_comment_url' => 'https://api.github.com/repos/agallou/test/pulls/comments{/number}',
    'comments_url' => 'https://api.github.com/repos/agallou/test/issues/1/comments',
    'statuses_url' => 'https://api.github.com/repos/agallou/test/statuses/c9cdc0e78c3d44d020c89f1ff8f0688cacfaee9e',
    'head' =>
        array (
            'label' => 'agallou:test1',
            'ref' => 'test1',
            'sha' => 'c9cdc0e78c3d44d020c89f1ff8f0688cacfaee9e',
            'user' =>
                array (
                    'login' => 'agallou',
                    'id' => 320372,
                    'avatar_url' => 'https://avatars.githubusercontent.com/u/320372?v=3',
                    'gravatar_id' => '',
                    'url' => 'https://api.github.com/users/agallou',
                    'html_url' => 'https://github.com/agallou',
                    'followers_url' => 'https://api.github.com/users/agallou/followers',
                    'following_url' => 'https://api.github.com/users/agallou/following{/other_user}',
                    'gists_url' => 'https://api.github.com/users/agallou/gists{/gist_id}',
                    'starred_url' => 'https://api.github.com/users/agallou/starred{/owner}{/repo}',
                    'subscriptions_url' => 'https://api.github.com/users/agallou/subscriptions',
                    'organizations_url' => 'https://api.github.com/users/agallou/orgs',
                    'repos_url' => 'https://api.github.com/users/agallou/repos',
                    'events_url' => 'https://api.github.com/users/agallou/events{/privacy}',
                    'received_events_url' => 'https://api.github.com/users/agallou/received_events',
                    'type' => 'User',
                    'site_admin' => false,
                ),
            'repo' =>
                array (
                    'id' => 56427893,
                    'name' => 'test',
                    'full_name' => 'agallou/test',
                    'owner' =>
                        array (
                            'login' => 'agallou',
                            'id' => 320372,
                            'avatar_url' => 'https://avatars.githubusercontent.com/u/320372?v=3',
                            'gravatar_id' => '',
                            'url' => 'https://api.github.com/users/agallou',
                            'html_url' => 'https://github.com/agallou',
                            'followers_url' => 'https://api.github.com/users/agallou/followers',
                            'following_url' => 'https://api.github.com/users/agallou/following{/other_user}',
                            'gists_url' => 'https://api.github.com/users/agallou/gists{/gist_id}',
                            'starred_url' => 'https://api.github.com/users/agallou/starred{/owner}{/repo}',
                            'subscriptions_url' => 'https://api.github.com/users/agallou/subscriptions',
                            'organizations_url' => 'https://api.github.com/users/agallou/orgs',
                            'repos_url' => 'https://api.github.com/users/agallou/repos',
                            'events_url' => 'https://api.github.com/users/agallou/events{/privacy}',
                            'received_events_url' => 'https://api.github.com/users/agallou/received_events',
                            'type' => 'User',
                            'site_admin' => false,
                        ),
                    'private' => true,
                    'html_url' => 'https://github.com/agallou/test',
                    'description' => '',
                    'fork' => false,
                    'url' => 'https://api.github.com/repos/agallou/test',
                    'forks_url' => 'https://api.github.com/repos/agallou/test/forks',
                    'keys_url' => 'https://api.github.com/repos/agallou/test/keys{/key_id}',
                    'collaborators_url' => 'https://api.github.com/repos/agallou/test/collaborators{/collaborator}',
                    'teams_url' => 'https://api.github.com/repos/agallou/test/teams',
                    'hooks_url' => 'https://api.github.com/repos/agallou/test/hooks',
                    'issue_events_url' => 'https://api.github.com/repos/agallou/test/issues/events{/number}',
                    'events_url' => 'https://api.github.com/repos/agallou/test/events',
                    'assignees_url' => 'https://api.github.com/repos/agallou/test/assignees{/user}',
                    'branches_url' => 'https://api.github.com/repos/agallou/test/branches{/branch}',
                    'tags_url' => 'https://api.github.com/repos/agallou/test/tags',
                    'blobs_url' => 'https://api.github.com/repos/agallou/test/git/blobs{/sha}',
                    'git_tags_url' => 'https://api.github.com/repos/agallou/test/git/tags{/sha}',
                    'git_refs_url' => 'https://api.github.com/repos/agallou/test/git/refs{/sha}',
                    'trees_url' => 'https://api.github.com/repos/agallou/test/git/trees{/sha}',
                    'statuses_url' => 'https://api.github.com/repos/agallou/test/statuses/{sha}',
                    'languages_url' => 'https://api.github.com/repos/agallou/test/languages',
                    'stargazers_url' => 'https://api.github.com/repos/agallou/test/stargazers',
                    'contributors_url' => 'https://api.github.com/repos/agallou/test/contributors',
                    'subscribers_url' => 'https://api.github.com/repos/agallou/test/subscribers',
                    'subscription_url' => 'https://api.github.com/repos/agallou/test/subscription',
                    'commits_url' => 'https://api.github.com/repos/agallou/test/commits{/sha}',
                    'git_commits_url' => 'https://api.github.com/repos/agallou/test/git/commits{/sha}',
                    'comments_url' => 'https://api.github.com/repos/agallou/test/comments{/number}',
                    'issue_comment_url' => 'https://api.github.com/repos/agallou/test/issues/comments{/number}',
                    'contents_url' => 'https://api.github.com/repos/agallou/test/contents/{+path}',
                    'compare_url' => 'https://api.github.com/repos/agallou/test/compare/{base}...{head}',
                    'merges_url' => 'https://api.github.com/repos/agallou/test/merges',
                    'archive_url' => 'https://api.github.com/repos/agallou/test/{archive_format}{/ref}',
                    'downloads_url' => 'https://api.github.com/repos/agallou/test/downloads',
                    'issues_url' => 'https://api.github.com/repos/agallou/test/issues{/number}',
                    'pulls_url' => 'https://api.github.com/repos/agallou/test/pulls{/number}',
                    'milestones_url' => 'https://api.github.com/repos/agallou/test/milestones{/number}',
                    'notifications_url' => 'https://api.github.com/repos/agallou/test/notifications{?since,all,participating}',
                    'labels_url' => 'https://api.github.com/repos/agallou/test/labels{/name}',
                    'releases_url' => 'https://api.github.com/repos/agallou/test/releases{/id}',
                    'deployments_url' => 'https://api.github.com/repos/agallou/test/deployments',
                    'created_at' => '2016-04-17T09:03:49Z',
                    'updated_at' => '2016-04-17T09:03:49Z',
                    'pushed_at' => '2016-04-17T09:11:28Z',
                    'git_url' => 'git://github.com/agallou/test.git',
                    'ssh_url' => 'git@github.com:agallou/test.git',
                    'clone_url' => 'https://github.com/agallou/test.git',
                    'svn_url' => 'https://github.com/agallou/test',
                    'homepage' => NULL,
                    'size' => 0,
                    'stargazers_count' => 0,
                    'watchers_count' => 0,
                    'language' => NULL,
                    'has_issues' => true,
                    'has_downloads' => true,
                    'has_wiki' => true,
                    'has_pages' => false,
                    'forks_count' => 0,
                    'mirror_url' => NULL,
                    'open_issues_count' => 1,
                    'forks' => 0,
                    'open_issues' => 1,
                    'watchers' => 0,
                    'default_branch' => 'master',
                ),
        ),
    'base' =>
        array (
            'label' => 'agallou:master',
            'ref' => 'master',
            'sha' => '522de47dc4948e35a05107bfee32c159167a9762',
            'user' =>
                array (
                    'login' => 'agallou',
                    'id' => 320372,
                    'avatar_url' => 'https://avatars.githubusercontent.com/u/320372?v=3',
                    'gravatar_id' => '',
                    'url' => 'https://api.github.com/users/agallou',
                    'html_url' => 'https://github.com/agallou',
                    'followers_url' => 'https://api.github.com/users/agallou/followers',
                    'following_url' => 'https://api.github.com/users/agallou/following{/other_user}',
                    'gists_url' => 'https://api.github.com/users/agallou/gists{/gist_id}',
                    'starred_url' => 'https://api.github.com/users/agallou/starred{/owner}{/repo}',
                    'subscriptions_url' => 'https://api.github.com/users/agallou/subscriptions',
                    'organizations_url' => 'https://api.github.com/users/agallou/orgs',
                    'repos_url' => 'https://api.github.com/users/agallou/repos',
                    'events_url' => 'https://api.github.com/users/agallou/events{/privacy}',
                    'received_events_url' => 'https://api.github.com/users/agallou/received_events',
                    'type' => 'User',
                    'site_admin' => false,
                ),
            'repo' =>
                array (
                    'id' => 56427893,
                    'name' => 'test',
                    'full_name' => 'agallou/test',
                    'owner' =>
                        array (
                            'login' => 'agallou',
                            'id' => 320372,
                            'avatar_url' => 'https://avatars.githubusercontent.com/u/320372?v=3',
                            'gravatar_id' => '',
                            'url' => 'https://api.github.com/users/agallou',
                            'html_url' => 'https://github.com/agallou',
                            'followers_url' => 'https://api.github.com/users/agallou/followers',
                            'following_url' => 'https://api.github.com/users/agallou/following{/other_user}',
                            'gists_url' => 'https://api.github.com/users/agallou/gists{/gist_id}',
                            'starred_url' => 'https://api.github.com/users/agallou/starred{/owner}{/repo}',
                            'subscriptions_url' => 'https://api.github.com/users/agallou/subscriptions',
                            'organizations_url' => 'https://api.github.com/users/agallou/orgs',
                            'repos_url' => 'https://api.github.com/users/agallou/repos',
                            'events_url' => 'https://api.github.com/users/agallou/events{/privacy}',
                            'received_events_url' => 'https://api.github.com/users/agallou/received_events',
                            'type' => 'User',
                            'site_admin' => false,
                        ),
                    'private' => true,
                    'html_url' => 'https://github.com/agallou/test',
                    'description' => '',
                    'fork' => false,
                    'url' => 'https://api.github.com/repos/agallou/test',
                    'forks_url' => 'https://api.github.com/repos/agallou/test/forks',
                    'keys_url' => 'https://api.github.com/repos/agallou/test/keys{/key_id}',
                    'collaborators_url' => 'https://api.github.com/repos/agallou/test/collaborators{/collaborator}',
                    'teams_url' => 'https://api.github.com/repos/agallou/test/teams',
                    'hooks_url' => 'https://api.github.com/repos/agallou/test/hooks',
                    'issue_events_url' => 'https://api.github.com/repos/agallou/test/issues/events{/number}',
                    'events_url' => 'https://api.github.com/repos/agallou/test/events',
                    'assignees_url' => 'https://api.github.com/repos/agallou/test/assignees{/user}',
                    'branches_url' => 'https://api.github.com/repos/agallou/test/branches{/branch}',
                    'tags_url' => 'https://api.github.com/repos/agallou/test/tags',
                    'blobs_url' => 'https://api.github.com/repos/agallou/test/git/blobs{/sha}',
                    'git_tags_url' => 'https://api.github.com/repos/agallou/test/git/tags{/sha}',
                    'git_refs_url' => 'https://api.github.com/repos/agallou/test/git/refs{/sha}',
                    'trees_url' => 'https://api.github.com/repos/agallou/test/git/trees{/sha}',
                    'statuses_url' => 'https://api.github.com/repos/agallou/test/statuses/{sha}',
                    'languages_url' => 'https://api.github.com/repos/agallou/test/languages',
                    'stargazers_url' => 'https://api.github.com/repos/agallou/test/stargazers',
                    'contributors_url' => 'https://api.github.com/repos/agallou/test/contributors',
                    'subscribers_url' => 'https://api.github.com/repos/agallou/test/subscribers',
                    'subscription_url' => 'https://api.github.com/repos/agallou/test/subscription',
                    'commits_url' => 'https://api.github.com/repos/agallou/test/commits{/sha}',
                    'git_commits_url' => 'https://api.github.com/repos/agallou/test/git/commits{/sha}',
                    'comments_url' => 'https://api.github.com/repos/agallou/test/comments{/number}',
                    'issue_comment_url' => 'https://api.github.com/repos/agallou/test/issues/comments{/number}',
                    'contents_url' => 'https://api.github.com/repos/agallou/test/contents/{+path}',
                    'compare_url' => 'https://api.github.com/repos/agallou/test/compare/{base}...{head}',
                    'merges_url' => 'https://api.github.com/repos/agallou/test/merges',
                    'archive_url' => 'https://api.github.com/repos/agallou/test/{archive_format}{/ref}',
                    'downloads_url' => 'https://api.github.com/repos/agallou/test/downloads',
                    'issues_url' => 'https://api.github.com/repos/agallou/test/issues{/number}',
                    'pulls_url' => 'https://api.github.com/repos/agallou/test/pulls{/number}',
                    'milestones_url' => 'https://api.github.com/repos/agallou/test/milestones{/number}',
                    'notifications_url' => 'https://api.github.com/repos/agallou/test/notifications{?since,all,participating}',
                    'labels_url' => 'https://api.github.com/repos/agallou/test/labels{/name}',
                    'releases_url' => 'https://api.github.com/repos/agallou/test/releases{/id}',
                    'deployments_url' => 'https://api.github.com/repos/agallou/test/deployments',
                    'created_at' => '2016-04-17T09:03:49Z',
                    'updated_at' => '2016-04-17T09:03:49Z',
                    'pushed_at' => '2016-04-17T09:11:28Z',
                    'git_url' => 'git://github.com/agallou/test.git',
                    'ssh_url' => 'git@github.com:agallou/test.git',
                    'clone_url' => 'https://github.com/agallou/test.git',
                    'svn_url' => 'https://github.com/agallou/test',
                    'homepage' => NULL,
                    'size' => 0,
                    'stargazers_count' => 0,
                    'watchers_count' => 0,
                    'language' => NULL,
                    'has_issues' => true,
                    'has_downloads' => true,
                    'has_wiki' => true,
                    'has_pages' => false,
                    'forks_count' => 0,
                    'mirror_url' => NULL,
                    'open_issues_count' => 1,
                    'forks' => 0,
                    'open_issues' => 1,
                    'watchers' => 0,
                    'default_branch' => 'master',
                ),
        ),
    '_links' =>
        array (
            'self' =>
                array (
                    'href' => 'https://api.github.com/repos/agallou/test/pulls/1',
                ),
            'html' =>
                array (
                    'href' => 'https://github.com/agallou/test/pull/1',
                ),
            'issue' =>
                array (
                    'href' => 'https://api.github.com/repos/agallou/test/issues/1',
                ),
            'comments' =>
                array (
                    'href' => 'https://api.github.com/repos/agallou/test/issues/1/comments',
                ),
            'review_comments' =>
                array (
                    'href' => 'https://api.github.com/repos/agallou/test/pulls/1/comments',
                ),
            'review_comment' =>
                array (
                    'href' => 'https://api.github.com/repos/agallou/test/pulls/comments{/number}',
                ),
            'commits' =>
                array (
                    'href' => 'https://api.github.com/repos/agallou/test/pulls/1/commits',
                ),
            'statuses' =>
                array (
                    'href' => 'https://api.github.com/repos/agallou/test/statuses/c9cdc0e78c3d44d020c89f1ff8f0688cacfaee9e',
                ),
        ),
    'merged' => false,
    'mergeable' => true,
    'mergeable_state' => 'clean',
    'merged_by' => NULL,
    'comments' => 2,
    'review_comments' => 1,
    'commits' => 1,
    'additions' => 1,
    'deletions' => 0,
    'changed_files' => 1,
);
