<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace HipchatConnectTools\UnreviewedPr\Model\ProjectDb\PublicSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Phinxlog
 *
 * Structure class for relation public.phinxlog.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Phinxlog extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.phinxlog')
            ->setPrimaryKey(['version'])
            ->addField('version', 'int8')
            ->addField('migration_name', 'varchar')
            ->addField('start_time', 'timestamp')
            ->addField('end_time', 'timestamp')
            ;
    }
}
