<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace HipchatConnectTools\UnreviewedPr\Model\ProjectDb\PublicSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Repository
 *
 * Structure class for relation public.repository.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Repository extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.repository')
            ->setPrimaryKey(['id'])
            ->addField('id', 'varchar')
            ->addField('full_name', 'varchar')
            ->addField('github_webhook_secret', 'varchar')
            ;
    }
}
