<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace HipchatConnectTools\UnreviewedPr\Model\ProjectDb\PublicSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Subsribers
 *
 * Structure class for relation public.subsribers.
 * 
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 *
 *
 *
 * @see RowStructure
 */
class Subsribers extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('public.subsribers')
            ->setPrimaryKey(['hipchat_oauth_id'])
            ->addField('hipchat_oauth_id', 'varchar')
            ->addField('hipchat_oauth_secret', 'varchar')
            ->addField('rooom_id', 'varchar')
            ->addField('group_id', 'varchar')
            ->addField('github_token', 'varchar')
            ;
    }
}
